//=============================================================================
// SDRAM Memory Top Module with AXI4-Lite Interface + CDC
//=============================================================================
// Top-level wrapper combining:
//   1. axil_cdc_bridge  — AXI-Lite CDC (clk_50mhz → clk_100mhz)
//   2. axi_sdram_bridge — random-access AXI-to-SDRAM FIFO bridge
//   3. Sdram_Control    — Terasic SDRAM controller with internal PLL
//
// External (SoC) side runs on clk_50mhz.
// SDRAM controller + bridge run on clk_100mhz (generated by PLL).
//
// Memory: 64 MB SDRAM (IS42S16320D on DE10-Lite)
// Interface: AXI4-Lite 32-bit
//
// Author : Z-Core SoC
// Date   : 2026-04-05
//=============================================================================

module sdram_axi_top #(
    parameter AXI_ADDR_WIDTH = 26,      // 64 MB address space
    parameter AXI_DATA_WIDTH = 32       // 32-bit data
)(
    //=========================================================================
    // Clock and Reset
    //=========================================================================
    input  wire                         clk_50mhz,      // 50 MHz system clock
    input  wire                         rst_n,          // Active-low reset

    //=========================================================================
    // AXI4-Lite Slave Interface (CPU / SoC domain, 50 MHz)
    //=========================================================================
    // Write Address Channel
    input  wire [AXI_ADDR_WIDTH-1:0]    s_axi_awaddr,
    input  wire                         s_axi_awvalid,
    output wire                         s_axi_awready,

    // Write Data Channel
    input  wire [AXI_DATA_WIDTH-1:0]    s_axi_wdata,
    input  wire [3:0]                   s_axi_wstrb,
    input  wire                         s_axi_wvalid,
    output wire                         s_axi_wready,

    // Write Response Channel
    output wire [1:0]                   s_axi_bresp,
    output wire                         s_axi_bvalid,
    input  wire                         s_axi_bready,

    // Read Address Channel
    input  wire [AXI_ADDR_WIDTH-1:0]    s_axi_araddr,
    input  wire                         s_axi_arvalid,
    output wire                         s_axi_arready,

    // Read Data Channel
    output wire [AXI_DATA_WIDTH-1:0]    s_axi_rdata,
    output wire [1:0]                   s_axi_rresp,
    output wire                         s_axi_rvalid,
    input  wire                         s_axi_rready,

    //=========================================================================
    // SDRAM Physical Interface (directly to FPGA pins)
    //=========================================================================
    output wire [12:0]                  DRAM_ADDR,
    output wire [1:0]                   DRAM_BA,
    output wire                         DRAM_CAS_N,
    output wire                         DRAM_CKE,
    output wire                         DRAM_CLK,
    output wire                         DRAM_CS_N,
    inout  wire [15:0]                  DRAM_DQ,
    output wire                         DRAM_LDQM,
    output wire                         DRAM_RAS_N,
    output wire                         DRAM_UDQM,
    output wire                         DRAM_WE_N,

    //=========================================================================
    // Debug / Status
    //=========================================================================
    output wire [4:0]                   debug_state,
    output wire                         debug_busy,
    output wire                         debug_wr_full,
    output wire                         debug_rd_empty,
    output wire [31:0]                  debug_wr_count,
    output wire [31:0]                  debug_rd_count,
    output wire                         debug_error,

    // Clock output for external modules
    output wire                         clk_sdram       // 100 MHz SDRAM clock
);

    //=========================================================================
    // Internal Wires
    //=========================================================================

    // 100 MHz clock from PLL inside Sdram_Control
    wire clk_100mhz;

    //=========================================================================
    // Reset synchronizer for 100 MHz domain (Bug fix #3)
    //
    // KEY[0] (rst_n) is asynchronous relative to clk_100mhz. A 2-FF
    // synchronizer ensures clean de-assertion in the 100 MHz domain.
    // Assertion is still asynchronous (negedge rst_n drives the FFs into
    // reset instantly), which is the safe direction.
    //=========================================================================
    reg [1:0] rst_n_100_sync;
    always @(posedge clk_100mhz or negedge rst_n) begin
        if (!rst_n) rst_n_100_sync <= 2'b00;
        else        rst_n_100_sync <= {rst_n_100_sync[0], 1'b1};
    end
    wire rst_n_100 = rst_n_100_sync[1];

    // --- CDC bridge master-side → SDRAM bridge slave-side (100 MHz) ---
    wire [AXI_ADDR_WIDTH-1:0]   cdc_m_awaddr;
    wire                        cdc_m_awvalid;
    wire                        cdc_m_awready;
    wire [AXI_DATA_WIDTH-1:0]   cdc_m_wdata;
    wire [3:0]                  cdc_m_wstrb;
    wire                        cdc_m_wvalid;
    wire                        cdc_m_wready;
    wire [1:0]                  cdc_m_bresp;
    wire                        cdc_m_bvalid;
    wire                        cdc_m_bready;
    wire [AXI_ADDR_WIDTH-1:0]   cdc_m_araddr;
    wire                        cdc_m_arvalid;
    wire                        cdc_m_arready;
    wire [AXI_DATA_WIDTH-1:0]   cdc_m_rdata;
    wire [1:0]                  cdc_m_rresp;
    wire                        cdc_m_rvalid;
    wire                        cdc_m_rready;

    // --- SDRAM bridge → controller FIFO wires (100 MHz) ---
    wire [15:0] bridge_wr_data;
    wire        bridge_wr;
    wire [24:0] bridge_wr_addr;
    wire [24:0] bridge_wr_max_addr;
    wire [8:0]  bridge_wr_length;
    wire        bridge_wr_load;
    wire        bridge_wr_full;
    wire [15:0] bridge_wr_use;
    wire [15:0] bridge_wr_fifo_rdusedw;

    wire [15:0] bridge_rd_data;
    wire        bridge_rd;
    wire [24:0] bridge_rd_addr;
    wire [24:0] bridge_rd_max_addr;
    wire [8:0]  bridge_rd_length;
    wire        bridge_rd_load;
    wire        bridge_rd_empty;
    wire [15:0] bridge_rd_use;

    wire [1:0]  sdram_cs_n;

    //=========================================================================
    // CDC Bridge: 50 MHz (SoC) → 100 MHz (SDRAM)
    //=========================================================================
    axil_cdc_bridge #(
        .ADDR_WIDTH(AXI_ADDR_WIDTH),
        .DATA_WIDTH(AXI_DATA_WIDTH),
        .STRB_WIDTH(4)
    ) u_cdc (
        // Slave side (50 MHz — CPU)
        .clk_s          (clk_50mhz),
        .rst_s_n        (rst_n),

        .s_axil_awaddr  (s_axi_awaddr),
        .s_axil_awvalid (s_axi_awvalid),
        .s_axil_awready (s_axi_awready),
        .s_axil_wdata   (s_axi_wdata),
        .s_axil_wstrb   (s_axi_wstrb),
        .s_axil_wvalid  (s_axi_wvalid),
        .s_axil_wready  (s_axi_wready),
        .s_axil_bresp   (s_axi_bresp),
        .s_axil_bvalid  (s_axi_bvalid),
        .s_axil_bready  (s_axi_bready),

        .s_axil_araddr  (s_axi_araddr),
        .s_axil_arvalid (s_axi_arvalid),
        .s_axil_arready (s_axi_arready),
        .s_axil_rdata   (s_axi_rdata),
        .s_axil_rresp   (s_axi_rresp),
        .s_axil_rvalid  (s_axi_rvalid),
        .s_axil_rready  (s_axi_rready),

        // Master side (100 MHz — SDRAM)
        .clk_m          (clk_100mhz),
        .rst_m_n        (rst_n_100),

        .m_axil_awaddr  (cdc_m_awaddr),
        .m_axil_awvalid (cdc_m_awvalid),
        .m_axil_awready (cdc_m_awready),
        .m_axil_wdata   (cdc_m_wdata),
        .m_axil_wstrb   (cdc_m_wstrb),
        .m_axil_wvalid  (cdc_m_wvalid),
        .m_axil_wready  (cdc_m_wready),
        .m_axil_bresp   (cdc_m_bresp),
        .m_axil_bvalid  (cdc_m_bvalid),
        .m_axil_bready  (cdc_m_bready),

        .m_axil_araddr  (cdc_m_araddr),
        .m_axil_arvalid (cdc_m_arvalid),
        .m_axil_arready (cdc_m_arready),
        .m_axil_rdata   (cdc_m_rdata),
        .m_axil_rresp   (cdc_m_rresp),
        .m_axil_rvalid  (cdc_m_rvalid),
        .m_axil_rready  (cdc_m_rready)
    );

    //=========================================================================
    // AXI4-Lite ↔ SDRAM Bridge (100 MHz domain)
    //=========================================================================
    axi_sdram_bridge #(
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .SDRAM_DATA_WIDTH(16),
        .SDRAM_ADDR_WIDTH(25)
    ) u_bridge (
        .clk            (clk_100mhz),
        .rst_n          (rst_n_100),

        // AXI4-Lite (from CDC master side)
        .s_axi_awaddr   (cdc_m_awaddr),
        .s_axi_awvalid  (cdc_m_awvalid),
        .s_axi_awready  (cdc_m_awready),
        .s_axi_wdata    (cdc_m_wdata),
        .s_axi_wstrb    (cdc_m_wstrb),
        .s_axi_wvalid   (cdc_m_wvalid),
        .s_axi_wready   (cdc_m_wready),
        .s_axi_bresp    (cdc_m_bresp),
        .s_axi_bvalid   (cdc_m_bvalid),
        .s_axi_bready   (cdc_m_bready),
        .s_axi_araddr   (cdc_m_araddr),
        .s_axi_arvalid  (cdc_m_arvalid),
        .s_axi_arready  (cdc_m_arready),
        .s_axi_rdata    (cdc_m_rdata),
        .s_axi_rresp    (cdc_m_rresp),
        .s_axi_rvalid   (cdc_m_rvalid),
        .s_axi_rready   (cdc_m_rready),

        // SDRAM controller FIFO interface
        .sdram_wr_data      (bridge_wr_data),
        .sdram_wr           (bridge_wr),
        .sdram_wr_addr      (bridge_wr_addr),
        .sdram_wr_max_addr  (bridge_wr_max_addr),
        .sdram_wr_length    (bridge_wr_length),
        .sdram_wr_load      (bridge_wr_load),
        .sdram_wr_full      (bridge_wr_full),
        .sdram_wr_use       (bridge_wr_use),
        .sdram_wr_fifo_rdusedw (bridge_wr_fifo_rdusedw),

        .sdram_rd_data      (bridge_rd_data),
        .sdram_rd           (bridge_rd),
        .sdram_rd_addr      (bridge_rd_addr),
        .sdram_rd_max_addr  (bridge_rd_max_addr),
        .sdram_rd_length    (bridge_rd_length),
        .sdram_rd_load      (bridge_rd_load),
        .sdram_rd_empty     (bridge_rd_empty),
        .sdram_rd_use       (bridge_rd_use),

        // Debug
        .debug_state        (debug_state),
        .debug_busy         (debug_busy),
        .debug_wr_full      (debug_wr_full),
        .debug_rd_empty     (debug_rd_empty),
        .debug_wr_count     (debug_wr_count),
        .debug_rd_count     (debug_rd_count),
        .debug_error        (debug_error)
    );

    //=========================================================================
    // Terasic SDRAM Controller (100 MHz domain)
    //=========================================================================
    Sdram_Control u_sdram_ctrl (
        // Host side
        .REF_CLK    (clk_50mhz),
        .RESET_N    (rst_n_100),
        .CLK        (clk_100mhz),       // Output: 100 MHz from PLL

        // Write FIFO interface
        .WR_DATA    (bridge_wr_data),
        .WR         (bridge_wr),
        .WR_ADDR    (bridge_wr_addr),
        .WR_MAX_ADDR(bridge_wr_max_addr),
        .WR_LENGTH  (bridge_wr_length),
        .WR_LOAD    (bridge_wr_load),
        .WR_CLK     (clk_100mhz),
        .WR_FULL    (bridge_wr_full),
        .WR_USE     (bridge_wr_use),
        .WR_FIFO_RDUSEDW (bridge_wr_fifo_rdusedw),

        // Read FIFO interface
        .RD_DATA    (bridge_rd_data),
        .RD         (bridge_rd),
        .RD_ADDR    (bridge_rd_addr),
        .RD_MAX_ADDR(bridge_rd_max_addr),
        .RD_LENGTH  (bridge_rd_length),
        .RD_LOAD    (bridge_rd_load),
        .RD_CLK     (clk_100mhz),
        .RD_EMPTY   (bridge_rd_empty),
        .RD_USE     (bridge_rd_use),

        // SDRAM physical interface
        .SA         (DRAM_ADDR),
        .BA         (DRAM_BA),
        .CS_N       (sdram_cs_n),
        .CKE        (DRAM_CKE),
        .RAS_N      (DRAM_RAS_N),
        .CAS_N      (DRAM_CAS_N),
        .WE_N       (DRAM_WE_N),
        .DQ         (DRAM_DQ),
        .DQM        ({DRAM_UDQM, DRAM_LDQM}),
        .SDR_CLK    (DRAM_CLK)
    );

    // DE10-Lite has single SDRAM chip, use CS_N[0]
    assign DRAM_CS_N = sdram_cs_n[0];

    // Expose 100 MHz clock for external modules
    assign clk_sdram = clk_100mhz;

endmodule
